image: Visual Studio 2019

environment:
  
  matrix:
  - solution_path: hw3/LambdaInterpreter/LambdaInterpreter.sln
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
