  
image: Visual Studio 2019

environment:
  
  matrix:
  - solution_path: hw4/bracketBalance/bracketBalance.sln
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
